# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1024)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('date_modified', models.DateTimeField(verbose_name='date modified')),
                ('date_closed', models.DateTimeField(verbose_name='date closed')),
                ('assigned', models.ManyToManyField(related_name='assigned', to='polls.User')),
                ('issue_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_author', to='polls.User')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='polls.Repository')),
            ],
        ),
    ]
