# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='file',
            name='folder_obj',
        ),
        migrations.RemoveField(
            model_name='file',
            name='object_ptr',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='object_ptr',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='repository_folder',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='subfolder',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_author',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='version',
            name='object_version',
        ),
        migrations.RemoveField(
            model_name='version',
            name='user_version',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
