# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('object_version', models.ManyToManyField(related_name='object_version', to='object.Object')),
                ('user_version', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_version', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
