# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_auto_20160322_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='subfolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='object.Folder'),
        ),
    ]
